name: Vulnerability Scanning

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  scan-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: table
        output: 'trivy_report.txt'
        severity: 'HIGH'
        
    - name: Upload Trivy report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy_report.txt

    - name: Vulnarability check success?
      id: check
      run: |
        if grep -q 'Total: 0' trivy_report.txt; then
          echo "Success"
          echo "::set-output name=build_image::true"
        else
          echo "Fail"
          echo "::set-output name=build_image::false"

    - name: Set up Docker BuildX
      if: steps.check.outputs.build_image == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: steps.check.outputs.build_image == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker Build and Push
      if: steps.check.outputs.build_image == 'true'
      uses: docker/build-push-action@v5
      with:
         push: true
         tags: reminious/gg:${{ github.sha }}
         file: ./Dockerfile

         
    - name: Install Cosign Tool
      if: steps.check.outputs.build_image == 'true'
      uses: sigstore/cosign-installer@v3.1.2

    - name: Write Signing Key
      if: steps.check.outputs.build_image == 'true'
      run: 'echo "$KEY" > cosign.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        
    - name: Sign Docker Image
      if: steps.check.outputs.build_image == 'true'
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: 
        echo 'y' | cosign sign --key cosign.key reminious/gg:${{ github.sha }}
      
