name: Vulnerability Scanning

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  scan-vulnerabilities:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: table
        output: 'trivy_report.txt'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-report
        path: trivy_report.txt

    - name: Set Image Tag
      run: echo "fred/go-fortune:${GITHUB_SHA}" >> tag.txt

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v5
      with:
         push: true
         tags: reminious/gg:1.0.0
         file: ./Dockerfile
