name: Vulnerability Scanning

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  scan-vulnerabilities:
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: table
        output: 'trivy_report.txt'
        severity: 'CRITICAL'

    - name: Vulnerabilities Check Success?
      id: check
      run: |
        if grep -w 'Total' trivy_report.txt; then
          echo "Fail!"
          echo "build_image=false" >> $GITHUB_ENV
        else
          echo "Success!"
          echo "build_image=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Get Short Commit
      run:
        echo "COMMIT_SHORT=`echo ${GITHUB_SHA} | cut -c 1-6`" >> $GITHUB_ENV

    # - name: Upload Trivy report
    #   uses: actions/upload-artifact@v3.1.3
    #   with:
    #     name: trivy-report
    #     path: trivy_report.txt

      #Success starts
    - name: Set up Docker BuildX
      if: env.build_image == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: env.build_image == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker Build and Push
      if: env.build_image == 'true'
      uses: docker/build-push-action@v5
      with:
         push: true
         tags: reminious/cicd_ca:${{ github.sha }}
         file: ./Dockerfile
         
    - name: Install Cosign Tool
      if: env.build_image == 'true'
      uses: sigstore/cosign-installer@v3.1.2

    - name: Write Signing Key
      if: env.build_image == 'true'
      run: 'echo "$KEY" > cosign.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        
    - name: Sign Docker Image
      if: env.build_image == 'true'
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: 
        echo 'y' | cosign sign --key cosign.key reminious/cicd_ca:${{ github.sha }}

    - name: Send Slack Message
      if: env.build_image == 'true'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: "./SuccContent.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOME_WEBHOOK
      #Success ends

      #Fail starts
    - name: Send Slack Message
      if: env.build_image == 'false'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload-file-path: "./FailContent.json"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOME_WEBHOOK
    
    - name: Upload Report File
      if: env.build_image == 'false'
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        file_type: 'text'
        file_path: trivy_report.txt
        title: 'trivy_report'
      #Fail ends
      
      
